### PR TITLE
DNS fix

### PR DESCRIPTION
**Pull request by ghost**
Switched dns.resolve with dns.lookup for speed and more reliable
functionality. #1

### CODE REVIEW

**Comment by Ashishjshetty** [comment]
Hi @alexbauman207 ,
I think dns resolve may be more reliable as lookup always uses host-file of a system first to check the host name address, where as in resolve it always resolves over internet. Check node [documentation](https://nodejs.org/api/dns.html#dns_implementation_considerations), also in there is:

> Though the call to dns.lookup() will be asynchronous from JavaScript's perspective, it is implemented       as a **synchronous** call to getaddrinfo(3) that runs on libuv's threadpool. Because libuv's threadpool has a fixed size, it means that if for whatever reason the call to getaddrinfo(3) takes a long time, other operations that could run on libuv's threadpool (such as filesystem operations) will experience degraded performance.

As you can see it may not be much of a performance improvement either . What do you think?

**Comment by ghost** [comment]
That makes sense. While I was looking things up trying to use this for my own project, I came across this on a [StackOverflow post](http://stackoverflow.com/questions/15270902/check-for-internet-connectivity-in-nodejs)

> While robertklep's solution works, it is far from being the best choice for this. It takes about 3 minutes for dns.resolve to timeout and give an error if you don't have an internet connection, while dns.lookup responds almost instantly with the error ENOTFOUND.

which seemed to be consistent with what I was experiencing in my limited testing: dns.resolve seems slow to conclude that the internet is down (and doesn't detect when the internet is back up, thought that might be some other issue).  I suppose an effective compromise might be to simply include both; replace 'dns' with 'resolve' and add an option to use 'lookup' as well.  

Incidentally, has dns.resolve worked consistently for you in your testing?  I'm curious if my setup is acting unusual.

**Comment by Ashishjshetty** [comment]
yes it worked for me, the default interval is 10 seconds for every check, I have included the test i did to check what you were saying i didn't experience any problem see [here](https://github.com/Ashishjshetty/is-connected/issues/1#issuecomment-246130458).And Yes i was thinking the same maybe include both and add a comment to readme pointing to the documentation. what do you think?

**Comment by Ashishjshetty** [comment]
you wont get an immediate event of disconnection as it is simply checking for disconnection every 10 seconds by default, you can change it to any thing less   by passing a seconds parameter to constructor eg: `let isConnectivity = new IsConnected(2000);` which will check every 2 seconds.

**Comment by Ashishjshetty** [comment]
i have tested it on windows and the behavior is  different. You should not face the problem on linux though. what OS are you testing on?

**Comment by ghost** [comment]
My PC is currently Windows 8.1.

**Comment by Ashishjshetty** [comment]
yes then that is why you faced the problem. I will just add dns resolve for linux and dns lookup for windows. And will add some notes in readme to explain why. Thank you for pointing this out, I would have never tested on windows.

**Comment by Ashishjshetty** [comment]
Hi @alexbauman207 i have made some changes and added OS check so resolve should work for linux and lookup for windows. changed my mind in adding both as for known performance reasons. Thanks for your input.

**Pull request closed without merging**
